package com.bpl.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ShipmentMethodAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentMethodAllPropertiesEquals(ShipmentMethod expected, ShipmentMethod actual) {
        assertShipmentMethodAutoGeneratedPropertiesEquals(expected, actual);
        assertShipmentMethodAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentMethodAllUpdatablePropertiesEquals(ShipmentMethod expected, ShipmentMethod actual) {
        assertShipmentMethodUpdatableFieldsEquals(expected, actual);
        assertShipmentMethodUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentMethodAutoGeneratedPropertiesEquals(ShipmentMethod expected, ShipmentMethod actual) {
        assertThat(expected)
            .as("Verify ShipmentMethod auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentMethodUpdatableFieldsEquals(ShipmentMethod expected, ShipmentMethod actual) {
        assertThat(expected)
            .as("Verify ShipmentMethod relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentMethodUpdatableRelationshipsEquals(ShipmentMethod expected, ShipmentMethod actual) {
        assertThat(expected)
            .as("Verify ShipmentMethod relationships")
            .satisfies(e -> assertThat(e.getParentType()).as("check parentType").isEqualTo(actual.getParentType()));
    }
}
