package com.lxisoft.organizationbackend.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ParentorganizationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParentorganizationAllPropertiesEquals(Parentorganization expected, Parentorganization actual) {
        assertParentorganizationAutoGeneratedPropertiesEquals(expected, actual);
        assertParentorganizationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParentorganizationAllUpdatablePropertiesEquals(Parentorganization expected, Parentorganization actual) {
        assertParentorganizationUpdatableFieldsEquals(expected, actual);
        assertParentorganizationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParentorganizationAutoGeneratedPropertiesEquals(Parentorganization expected, Parentorganization actual) {
        assertThat(expected)
            .as("Verify Parentorganization auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParentorganizationUpdatableFieldsEquals(Parentorganization expected, Parentorganization actual) {
        assertThat(expected)
            .as("Verify Parentorganization relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParentorganizationUpdatableRelationshipsEquals(Parentorganization expected, Parentorganization actual) {
        // empty method
    }
}
