package com.diviso.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FacilityTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFacilityTypeAllPropertiesEquals(FacilityType expected, FacilityType actual) {
        assertFacilityTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertFacilityTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFacilityTypeAllUpdatablePropertiesEquals(FacilityType expected, FacilityType actual) {
        assertFacilityTypeUpdatableFieldsEquals(expected, actual);
        assertFacilityTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFacilityTypeAutoGeneratedPropertiesEquals(FacilityType expected, FacilityType actual) {
        assertThat(expected)
            .as("Verify FacilityType auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFacilityTypeUpdatableFieldsEquals(FacilityType expected, FacilityType actual) {
        assertThat(expected)
            .as("Verify FacilityType relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFacilityTypeUpdatableRelationshipsEquals(FacilityType expected, FacilityType actual) {
        // empty method
    }
}
