package com.lxisofttech.invoice.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CurrencyTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCurrencyTypeAllPropertiesEquals(CurrencyType expected, CurrencyType actual) {
        assertCurrencyTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertCurrencyTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCurrencyTypeAllUpdatablePropertiesEquals(CurrencyType expected, CurrencyType actual) {
        assertCurrencyTypeUpdatableFieldsEquals(expected, actual);
        assertCurrencyTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCurrencyTypeAutoGeneratedPropertiesEquals(CurrencyType expected, CurrencyType actual) {
        assertThat(expected)
            .as("Verify CurrencyType auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCurrencyTypeUpdatableFieldsEquals(CurrencyType expected, CurrencyType actual) {
        assertThat(expected)
            .as("Verify CurrencyType relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCurrencyTypeUpdatableRelationshipsEquals(CurrencyType expected, CurrencyType actual) {
        // empty method
    }
}
